package('b-showcase')
	.extends('i-block')
	.dependencies(
		'b-header',
		'b-button',
		'b-calendar',
		'b-checkbox-group',
		'b-checkbox',
		'b-radio-button',
		'b-input',
		'b-v4-component-demo',
		'b-checkbox-group'
	);
